obj-m := basic_kernel_module.o




all:

	make ARCH=arm64 CROSS_COMPILE=/home/henley/adacore/e3-distrib-3.8-20210805-x86_64-linux-bin/wave/aarch64-linux-linux64/gnat/install/bin/aarch64-linux-gnu- -C /home/henley/cross/output M=/home/henley/adacore/repos/adacore_jetson/tmp modules

