obj-m := basic_kernel_module.o




all:

	make ARCH=arm CROSS_COMPILE=/home/henley/wave/arm-elf-linux64/gnat/install/bin/arm-eabi- -C /home/henley/adacore/repos/cross/linux_rp32 M=/home/henley/adacore/repos/incremental_ada_linux_driver/tmp modules

