obj-m := hello.o
hello-y := ../big_test/p__ada_linux_0.o ../rts-native-light/obj/s-secsta.o ../rts-native-light/obj/s-sssita.o ../rts-native-light/obj/s-gtidi3.o ../rts-native-light/obj/s-gtdmo3.o  ../rts-native-light/obj/s-gtumo4.o ../rts-native-light/obj/i-c.o

all:
	make ARCH=arm64 CROSS_COMPILE=/home/henley/adacore/e3-distrib-3.8-20210805-x86_64-linux-bin/wave/aarch64-linux-linux64/gnat/install/bin/aarch64-linux-gnu- -C /home/henley/cross/output M=/home/henley/adacore/repos/adacore_jetson/./hello modules
